---
- name: installing and launching filebeat and metricbeat
  hosts: webservers
  become: yes
  tasks:
  
  - name: download .deb file
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.4.0-amd64.deb
	
  - name: Install .deb file
    command: dpkg -i filebeat-7.4.0-amd64.deb
	
  - name: Copy the filebeat conf file
    copy:
	  src: /etc/ansible/files/filebeat-config.yml
	  dest: /etc/filebeat/filebeat.yml
	  
  - name: enable and configure system module
    command: filebeat modules enable system
	
  - name: setup filebeat 
    command: filebeat setup
	
  - name: start service
    command: service filebeat start
	
  - name: Enable filebeat
    systemd:
	  name: filebeat
	  enabled: yes
	  
  - name: Download the metricbeat .deb file
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.1-amd64.deb
	
  - name: Install .deb file
    command: dpkg -i metricbeat-7.6.1-amd64.deb
	
  - name: copy the metricbeat conf file
    copy:
	  src: /etc/ansible/files/metricbeat-config.yml
	  dest: /etc/metricbeat/metricbeat.yml
	  
  - name: enable docker
    command: metricbeat modules enable docker
	
  - name: start metricbeat
    command: metricbeat setup
	
  - name: enable metricbeat
    systemd:
	  name: metricbeat
	  enabled: yes
	  